#---------------------------------------#
#                                       #
#         LE BLOC DE LYSANDRE           #                    
#                                       #
#---------------------------------------#

# --------- LYSANDRE NORMAL (LN) -------#

image LN LN= "images/lysander/LN/side LN.png"
image LN talk1= "images/lysander/LN/side LN neutral talk.png"
image LN talk2= "images/lysander/LN/side LN neutral talk2.png"
image LN talk3= "images/lysander/LN/side LN neutral talk3.png"
image LN frown= "images/lysander/LN/side LN neutral frown.png"
image LN smirk= "images/lysander/LN/side LN neutral smirk.png"

image LN scowl= "images/lysander/LN/side LN angry scowl.png"
image LN snarky= "images/lysander/LN/side LN angry snarky.png"
image LN angryTalk1= "images/lysander/LN/side LN angry talk.png"
image LN angryTalk2= "images/lysander/LN/side LN angry talk2.png"
image LN angryTalk3= "images/lysander/LN/side LN angry talk3.png"
image LN resolve= "images/lysander/LN/side LN angry resolve.png"

image LN happyBase= "images/lysander/LN/side LN happy base.png"
image LN happySmile= "images/lysander/LN/side LN happy smirk.png"
image LN uwu= "images/lysander/LN/side LN happy uwu.png"

image LN blushHbase= "images/lysander/LN/side LN happy blush base.png"
image LN blushFlirt= "images/lysander/LN/side LN happy blush flirt.png"
image LN blushSmirkH= "images/lysander/LN/side LN happy blush smirk.png"
image LN blushNbase= "images/lysander/LN/side LN neutral blush base.png"
image LN blushFrown= "images/lysander/LN/side LN neutral blush frown.png"
image LN blushSmirkN= "images/lysander/LN/side LN neutral blush smirk.png"

image LN worryBase= "images/lysander/LN/side LN worry base.png"
image LN worrySad= "images/lysander/LN/side LN worry sad.png"
image LN worryPout= "images/lysander/LN/side LN worry pout.png"
image LN worryTalk1= "images/lysander/LN/side LN worry cry.png"
image LN worryTalk2= "images/lysander/LN/side LN worry talk.png"
image LN worryTalk3= "images/lysander/LN/side LN worry sad talk.png"
image LN worryOpen= "images/lysander/LN/side LN worry open.png"
image LN worryEarnest= "images/lysander/LN/side LN worry earnest.png"
# --- side images LN -----#
image side LN = "images/lysander/LN/side LN.png"
image side LN talk1= "images/lysander/LN/side LN neutral talk.png"
image side LN talk2= "images/lysander/LN/side LN neutral talk2.png"
image side LN talk3= "images/lysander/LN/side LN neutral talk3.png"
image side LN frown= "images/lysander/LN/side LN neutral frown.png"
image side LN smirk= "images/lysander/LN/side LN neutral smirk.png"

image side LN scowl= "images/lysander/LN/side LN angry scowl.png"
image side LN snarky= "images/lysander/LN/side LN angry snarky.png"
image side LN angryTalk1= "images/lysander/LN/side LN angry talk.png"
image side LN angryTalk2= "images/lysander/LN/side LN angry talk2.png"
image side LN angryTalk3= "images/lysander/LN/side LN angry talk3.png"
image side LN resolve= "images/lysander/LN/side LN angry resolve.png"

image side LN happyBase= "images/lysander/LN/side LN happy base.png"
image side LN happySmile= "images/lysander/LN/side LN happy smirk.png"
image side LN uwu= "images/lysander/LN/side LN happy uwu.png"

image side LN blushHbase= "images/lysander/LN/side LN happy blush base.png"
image side LN blushFlirt= "images/lysander/LN/side LN happy blush flirt.png"
image side LN blushSmirkH= "images/lysander/LN/side LN happy blush smirk.png"
image side LN blushNbase= "images/lysander/LN/side LN neutral blush base.png"
image side LN blushFrown= "images/lysander/LN/side LN neutral blush frown.png"
image side LN blushSmirkN= "images/lysander/LN/side LN neutral blush smirk.png"

image side LN worryBase= "images/lysander/LN/side LN worry base.png"
image side LN worrySad= "images/lysander/LN/side LN worry sad.png"
image side LN worryPout= "images/lysander/LN/side LN worry pout.png"
image side LN worryTalk1= "images/lysander/LN/side LN worry cry.png"
image side LN worryTalk2= "images/lysander/LN/side LN worry talk.png"
image side LN worryTalk3= "images/lysander/LN/side LN worry sad talk.png"
image side LN worryOpen= "images/lysander/LN/side LN worry open.png"
image side LN worryEarnest= "images/lysander/LN/side LN worry earnest.png"

# ---- LYSANDRE ENCHANTE (LE) ---- #

image LE LE= "images/lysander/LE/side LE happy base.png"
image LE droolH= "images/lysander/LE/side LE happy drool.png"
image LE teethH= "images/lysander/LE/side LE happy teeth.png"
image LE flirtH= "images/lysander/LE/side LE happy flirt.png"
image LE giddy= "images/lysander/LE/side LE happy giddy.png"
image LE frownH= "images/lysander/LE/side LE happy frown.png"
image LE pleadH= "images/lysander/LE/side LE happy plead.png"
image LE poutH= "images/lysander/LE/side LE happy pout.png"
image LE smileH= "images/lysander/LE/side LE happy smile.png"
image LE happyTalk1= "images/lysander/LE/side LE happy talk.png"
image LE happyTalk2= "images/lysander/LE/side LE happy talk2.png"
image LE happyTalk3= "images/lysander/LE/side LE happy talk3.png"

image LE BlushHBase= "images/lysander/LE/side LE happy blush base.png"
image LE BlushHDrool= "images/lysander/LE/side LE happy blush drool.png"
image LE BlushHFlirtCreep= "images/lysander/LE/side LE happy blush flirt creep.png"
image LE BlushHFlirt= "images/lysander/LE/side LE happy blush flirt.png"
image LE BlushHGiddy= "images/lysander/LE/side LE happy blush giddy.png"
image LE BlushHSmile= "images/lysander/LE/side LE happy blush smile.png"
image LE BlushHSquirm= "images/lysander/LE/side LE happy blush squirm.png"
image LE BlushHTeeth= "images/lysander/LE/side LE happy blush teeth.png"

image LE BlushWBase= "images/lysander/LE/side LE worry blush base.png"
image LE BlushWfrown= "images/lysander/LE/side LE worry blush frown.png"
image LE BlushWopen= "images/lysander/LE/side LE worry blush open.png"
image LE BlushWpout= "images/lysander/LE/side LE worry blush pout.png"
image LE BlushWsmile= "images/lysander/LE/side LE worry blush smile.png"
image LE BlushWsquirm= "images/lysander/LE/side LE worry blush squirm.png"
image LE BlushWtalk1= "images/lysander/LE/side LE worry blush talk.png"
image LE BlushWtalk2= "images/lysander/LE/side LE worry blush talk2.png"
image LE BlushWtalk3= "images/lysander/LE/side LE worry blush talk3.png"

image LE worryBase= "images/lysander/LE/side LE worry base.png"
image LE worryFrown= "images/lysander/LE/side LE worry frown.png"
image LE worryOpen= "images/lysander/LE/side LE worry open.png"
image LE worryPout= "images/lysander/LE/side LE worry pout.png"
image LE worrySmile= "images/lysander/LE/side LE worry smile.png"
image LE worrySquirm= "images/lysander/LE/side LE worry squirm.png"
image LE worryTalk1= "images/lysander/LE/side LE worry talk.png"
image LE worryTalk2= "images/lysander/LE/side LE worry talk2.png"
image LE worryTalk3= "images/lysander/LE/side LE worry talk3.png"

image LE angerBase= "images/lysander/LE/side LE anger base.png"
image LE angerDeranged= "images/lysander/LE/side LE anger deranged.png"
image LE angerFrown= "images/lysander/LE/side LE anger frown.png"
image LE angerGrin= "images/lysander/LE/side LE anger grin.png"
image LE angerSadistic= "images/lysander/LE/side LE anger sadistic.png"
image LE angerSmile= "images/lysander/LE/side LE anger smile.png"
image LE angerSquirm= "images/lysander/LE/side LE anger squirm.png"
image LE angerStun= "images/lysander/LE/side LE anger stun.png"
image LE angerTalk1= "images/lysander/LE/side LE anger talk.png"
image LE angerTalk2= "images/lysander/LE/side LE anger talk2.png"
image LE angerTalk3= "images/lysander/LE/side LE anger yell.png"

# ---- side ---- #

image side LE = "images/lysander/LE/side LE happy base.png"
image side LE droolH= "images/lysander/LE/side LE happy drool.png"
image side LE teethH= "images/lysander/LE/side LE happy teeth.png"
image side LE flirtH= "images/lysander/LE/side LE happy flirt.png"
image side LE giddy= "images/lysander/LE/side LE happy giddy.png"
image side LE frownH= "images/lysander/LE/side LE happy frown.png"
image side LE pleadH= "images/lysander/LE/side LE happy plead.png"
image side LE poutH= "images/lysander/LE/side LE happy pout.png"
image side LE smileH= "images/lysander/LE/side LE happy smile.png"
image side LE happyTalk1= "images/lysander/LE/side LE happy talk.png"
image side LE happyTalk2= "images/lysander/LE/side LE happy talk2.png"
image side LE happyTalk3= "images/lysander/LE/side LE happy talk3.png"

image side LE BlushHBase= "images/lysander/LE/side LE happy blush base.png"
image side LE BlushHDrool= "images/lysander/LE/side LE happy blush drool.png"
image side LE BlushHFlirtCreep= "images/lysander/LE/side LE happy blush flirt creep.png"
image side LE BlushHFlirt= "images/lysander/LE/side LE happy blush flirt.png"
image side LE BlushHGiddy= "images/lysander/LE/side LE happy blush giddy.png"
image side LE BlushHSmile= "images/lysander/LE/side LE happy blush smile.png"
image side LE BlushHSquirm= "images/lysander/LE/side LE happy blush squirm.png"
image side LE BlushHTeeth= "images/lysander/LE/side LE happy blush teeth.png"

image side LE BlushWBase= "images/lysander/LE/side LE worry blush base.png"
image side LE BlushWfrown= "images/lysander/LE/side LE worry blush frown.png"
image side LE BlushWopen= "images/lysander/LE/side LE worry blush open.png"
image side LE BlushWpout= "images/lysander/LE/side LE worry blush pout.png"
image side LE BlushWsmile= "images/lysander/LE/side LE worry blush smile.png"
image side LE BlushWsquirm= "images/lysander/LE/side LE worry blush squirm.png"
image side LE BlushWtalk1= "images/lysander/LE/side LE worry blush talk.png"
image side LE BlushWtalk2= "images/lysander/LE/side LE worry blush talk2.png"
image side LE BlushWtalk3= "images/lysander/LE/side LE worry blush talk3.png"

image side LE worryBase= "images/lysander/LE/side LE worry base.png"
image side LE worryFrown= "images/lysander/LE/side LE worry frown.png"
image side LE worryOpen= "images/lysander/LE/side LE worry open.png"
image side LE worryPout= "images/lysander/LE/side LE worry pout.png"
image side LE worrySmile= "images/lysander/LE/side LE worry smile.png"
image side LE worrySquirm= "images/lysander/LE/side LE worry squirm.png"
image side LE worryTalk1= "images/lysander/LE/side LE worry talk.png"
image side LE worryTalk2= "images/lysander/LE/side LE worry talk2.png"
image side LE worryTalk3= "images/lysander/LE/side LE worry talk3.png"

image side LE angerBase= "images/lysander/LE/side LE anger base.png"
image side LE angerDeranged= "images/lysander/LE/side LE anger deranged.png"
image side LE angerFrown= "images/lysander/LE/side LE anger frown.png"
image side LE angerGrin= "images/lysander/LE/side LE anger grin.png"
image side LE angerSadistic= "images/lysander/LE/side LE anger sadistic.png"
image side LE angerSmile= "images/lysander/LE/side LE anger smile.png"
image side LE angerSquirm= "images/lysander/LE/side LE anger squirm.png"
image side LE angerStun= "images/lysander/LE/side LE anger stun.png"
image side LE angerTalk1= "images/lysander/LE/side LE anger talk.png"
image side LE angerTalk2= "images/lysander/LE/side LE anger talk2.png"
image side LE angerTalk3= "images/lysander/LE/side LE anger yell.png"

# ----- LYSANDRE CHARME (LC)----------#
#-----------------------base images --------------------------#
# blackout
image LC bBase= "images/lysander/LC/side LC blackout base.png"
image LC bDeranged= "images/lysander/LC/side LC blackout deranged.png"
image LC bDrool= "images/lysander/LC/side LC blackout drool.png"
image LC bSquirm= "images/lysander/LC/side LC blackout squirm.png"
image LC bTeeth= "images/lysander/LC/side LC blackout teeth.png"
image LC bWobble= "images/lysander/LC/side LC blackout wobble.png"
#frown
image LC fBase ="images/lysander/LC/side LC frownBase.png"
image LC fOpen ="images/lysander/LC/side LC frownOpen.png"
image LC fScowl ="images/lysander/LC/side LC frownScowl.png"
image LC fSmirk ="images/lysander/LC/side LC frownSmirk.png"
image LC fSquirm ="images/lysander/LC/side LC frownSquirm.png"
image LC fTalk1 ="images/lysander/LC/side LC frownTalk.png"
image LC fTalk2 ="images/lysander/LC/side LC frownTalk2.png"
image LC fTalk3 ="images/lysander/LC/side LC frownTalk3.png"
#happy
image LC hBase="images/lysander/LC/side LC happyBase.png"
image LC hDeranged="images/lysander/LC/side LC happyDeranged.png"
image LC hDrool="images/lysander/LC/side LC happyDrool.png"
image LC hLaugh="images/lysander/LC/side LC happyLaugh.png"
image LC hTalk1="images/lysander/LC/side LC happyTalk.png"
image LC hTalk2="images/lysander/LC/side LC happyTalk2.png"
image LC hTalk3="images/lysander/LC/side LC happyTalk3.png"
image LC hTeeth="images/lysander/LC/side LC happyTeeth.png"
image LC hWobble="images/lysander/LC/side LC happyWobble.png"
#mad
image LC mCry="images/lysander/LC/side LC madCry.png"
image LC mDeranged="images/lysander/LC/side LC madDeranged.png"
image LC mDrool="images/lysander/LC/side LC madDrool.png"
image LC mFrown="images/lysander/LC/side LC madFrown.png"
image LC mLaugh="images/lysander/LC/side LC madLaugh.png"
image LC mOpen="images/lysander/LC/side LC madOpen.png"
image LC mPout="images/lysander/LC/side LC madPout.png"
image LC mSmirk="images/lysander/LC/side LC madSmirk.png"
image LC mSquirm="images/lysander/LC/side LC madSquirm.png"
image LC mTalk1="images/lysander/LC/side LC madTalk.png"
image LC mTalk2="images/lysander/LC/side LC madTalk2.png"
image LC mTalk3="images/lysander/LC/side LC madTalk3.png"
image LC mTalk4="images/lysander/LC/side LC madTalk4.png"
image LC mTeeth="images/lysander/LC/side LC madTeeth.png"
image LC mWobble="images/lysander/LC/side LC madWobble.png"
#neutral
image LC LC="images/lysander/LC/side LC neutralBase.png"
image LC nDeranged="images/lysander/LC/side LC neutralDeranged.png"
image LC nFrown="images/lysander/LC/side LC neutralFrown.png"
image LC nOpen="images/lysander/LC/side LC neutralOpen.png"
image LC nPout="images/lysander/LC/side LC neutralPout.png"
image LC nSmirk="images/lysander/LC/side LC neutralSmirk.png"
image LC nSquirm="images/lysander/LC/side LC neutralSquirm.png"
image LC nwuw="images/lysander/LC/side LC neutraluwu.png"
image LC nWobble="images/lysander/LC/side LC neutralWobble.png"
#worry
image LC wBase="images/lysander/LC/side LC worryBase.png"
image LC wDeranged="images/lysander/LC/side LC worryDeranged.png"
image LC wDrool="images/lysander/LC/side LC worryDrool.png"
image LC wFrown="images/lysander/LC/side LC worryFrown.png"
image LC wOpen="images/lysander/LC/side LC worryOpen.png"
image LC wPout="images/lysander/LC/side LC worryPout.png"
image LC wSad="images/lysander/LC/side LC worrySad.png"
image LC wSquirm="images/lysander/LC/side LC worrySquirm.png"
image LC wTalk1="images/lysander/LC/side LC worryTalk.png"
image LC wTalk2="images/lysander/LC/side LC worryTalk2.png"
image LC wTalk3="images/lysander/LC/side LC worryTalk3.png"
image LC wTeeth="images/lysander/LC/side LC worryTeeth.png"
image LC wWobble="images/lysander/LC/side LC worryWobble.png"

#--------------SIDE images ------------------ #
# blackout
image side LC bBase= "images/lysander/LC/side LC blackout base.png"
image side LC bDeranged= "images/lysander/LC/side LC blackout deranged.png"
image side LC bDrool= "images/lysander/LC/side LC blackout drool.png"
image side LC bSquirm= "images/lysander/LC/side LC blackout squirm.png"
image side LC bTeeth= "images/lysander/LC/side LC blackout teeth.png"
image side LC bWobble= "images/lysander/LC/side LC blackout wobble.png"
#frown
image side LC fBase ="images/lysander/LC/side LC frownBase.png"
image side LC fOpen ="images/lysander/LC/side LC frownOpen.png"
image side LC fScowl ="images/lysander/LC/side LC frownScowl.png"
image side LC fSmirk ="images/lysander/LC/side LC frownSmirk.png"
image side LC fSquirm ="images/lysander/LC/side LC frownSquirm.png"
image side LC fTalk1 ="images/lysander/LC/side LC frownTalk.png"
image side LC fTalk2 ="images/lysander/LC/side LC frownTalk2.png"
image side LC fTalk3 ="images/lysander/LC/side LC frownTalk3.png"
#happy
image side LC hBase="images/lysander/LC/side LC happyBase.png"
image side LC hDeranged="images/lysander/LC/side LC happyDeranged.png"
image side LC hDrool="images/lysander/LC/side LC happyDrool.png"
image side LC hLaugh="images/lysander/LC/side LC happyLaugh.png"
image side LC hTalk1="images/lysander/LC/side LC happyTalk.png"
image side LC hTalk2="images/lysander/LC/side LC happyTalk2.png"
image side LC hTalk3="images/lysander/LC/side LC happyTalk3.png"
image side LC hTeeth="images/lysander/LC/side LC happyTeeth.png"
image side LC hWobble="images/lysander/LC/side LC happyWobble.png"
#mad
image side LC mCry="images/lysander/LC/side LC madCry.png"
image side LC mDeranged="images/lysander/LC/side LC madDeranged.png"
image side LC mDrool="images/lysander/LC/side LC madDrool.png"
image side LC mFrown="images/lysander/LC/side LC madFrown.png"
image side LC mLaugh="images/lysander/LC/side LC madLaugh.png"
image side LC mOpen="images/lysander/LC/side LC madOpen.png"
image side LC mPout="images/lysander/LC/side LC madPout.png"
image side LC mSmirk="images/lysander/LC/side LC madSmirk.png"
image side LC mSquirm="images/lysander/LC/side LC madSquirm.png"
image side LC mTalk1="images/lysander/LC/side LC madTalk.png"
image side LC mTalk2="images/lysander/LC/side LC madTalk2.png"
image side LC mTalk3="images/lysander/LC/side LC madTalk3.png"
image side LC mTalk4="images/lysander/LC/side LC madTalk4.png"
image side LC mTeeth="images/lysander/LC/side LC madTeeth.png"
image side LC mWobble="images/lysander/LC/side LC madWobble.png"
#neutral
image side LC nBase="images/lysander/LC/side LC neutralBase.png"
image side LC nDeranged="images/lysander/LC/side LC neutralDeranged.png"
image side LC nFrown="images/lysander/LC/side LC neutralFrown.png"
image side LC nOpen="images/lysander/LC/side LC neutralOpen.png"
image side LC nPout="images/lysander/LC/side LC neutralPout.png"
image side LC nSmirk="images/lysander/LC/side LC neutralSmirk.png"
image side LC nSquirm="images/lysander/LC/side LC neutralSquirm.png"
image side LC nwuw="images/lysander/LC/side LC neutraluwu.png"
image side LC nWobble="images/lysander/LC/side LC neutralWobble.png"
#worry
image side LC wBase="images/lysander/LC/side LC worryBase.png"
image side LC wDeranged="images/lysander/LC/side LC worryDeranged.png"
image side LC wDrool="images/lysander/LC/side LC worryDrool.png"
image side LC wFrown="images/lysander/LC/side LC worryFrown.png"
image side LC wOpen="images/lysander/LC/side LC worryOpen.png"
image side LC wPout="images/lysander/LC/side LC worryPout.png"
image side LC wSad="images/lysander/LC/side LC worrySad.png"
image side LC wSquirm="images/lysander/LC/side LC worrySquirm.png"
image side LC wTalk1="images/lysander/LC/side LC worryTalk.png"
image side LC wTalk2="images/lysander/LC/side LC worryTalk2.png"
image side LC wTalk3="images/lysander/LC/side LC worryTalk3.png"
image side LC wTeeth="images/lysander/LC/side LC worryTeeth.png"
image side LC wWobble="images/lysander/LC/side LC worryWobble.png"
